# Dictionnaire de classification des 100 maladies par grande famille médicale
MALADIES_CLUSTER = {
    # --- Pneumologie ---
    'acute bronchiolitis': 'Pneumologie',
    'acute bronchitis': 'Pneumologie',
    'acute bronchospasm': 'Pneumologie',
    'asthma': 'Pneumologie',
    'chronic obstructive pulmonary disease (copd)': 'Pneumologie',
    'croup': 'Pneumologie',
    'obstructive sleep apnea (osa)': 'Pneumologie',
    'pneumonia': 'Pneumologie',

    # --- ORL ---
    'acute sinusitis': 'ORL',
    'common cold': 'ORL',
    'eustachian tube dysfunction (ear disorder)': 'ORL',
    'nose disorder': 'ORL',
    'otitis externa (swimmer\'s ear)': 'ORL',
    'otitis media': 'ORL',
    'strep throat': 'ORL',
    'ear drum damage': 'ORL',
    'sore throat': 'ORL',
    'coryza': 'ORL',
    'seasonal allergies (hay fever)': 'ORL',
    'congestion in chest': 'ORL',

    # --- Cardiologie ---
    'angina': 'Cardiologie',
    'heart attack': 'Cardiologie',
    'heart failure': 'Cardiologie',
    'hypertensive heart disease': 'Cardiologie',
    'sinus bradycardia': 'Cardiologie',

    # --- Gastro-entérologie & Néphrologie ---
    'acute kidney injury': 'Néphrologie',
    'acute pancreatitis': 'Gastro-entérologie',
    'cholecystitis': 'Gastro-entérologie',
    'chronic constipation': 'Gastro-entérologie',
    'diverticulitis': 'Gastro-entérologie',
    'esophagitis': 'Gastro-entérologie',
    'gallstone': 'Gastro-entérologie',
    'gastrointestinal hemorrhage': 'Gastro-entérologie',
    'hiatal hernia': 'Gastro-entérologie',
    'infectious gastroenteritis': 'Gastro-entérologie',
    'liver disease': 'Gastro-entérologie',
    'noninfectious gastroenteritis': 'Gastro-entérologie',
    'vomiting blood': 'Gastro-entérologie',
    'melena': 'Gastro-entérologie',
    'rectal bleeding': 'Gastro-entérologie',
    'constipation': 'Gastro-entérologie',
    'appendicitis': 'Gastro-entérologie',
    'rectal disorder': 'Gastro-entérologie',

    # --- Neurologie & Psychiatrie ---
    'anxiety': 'Psychiatrie',
    'depression': 'Psychiatrie',
    'panic disorder': 'Psychiatrie',
    'personality disorder': 'Psychiatrie',
    'schizophrenia': 'Psychiatrie',
    'concussion': 'Neurologie',
    'multiple sclerosis': 'Neurologie',
    'peripheral nerve disorder': 'Neurologie',
    'brachial neuritis': 'Neurologie',
    'delusions or hallucinations': 'Psychiatrie',
    'obsessions and compulsions': 'Psychiatrie',
    'antisocial behavior': 'Psychiatrie',
    'hysterical behavior': 'Psychiatrie',
    'complex regional pain syndrome': 'Neurologie',

    # --- Dermatologie & Ophtalmologie ---
    'actinic keratosis': 'Dermatologie',
    'allergy': 'Dermatologie',
    'conjunctivitis': 'Ophtalmologie',
    'conjunctivitis due to allergy': 'Ophtalmologie',
    'contact dermatitis': 'Dermatologie',
    'cornea infection': 'Ophtalmologie',
    'diaper rash': 'Dermatologie',
    'eczema': 'Dermatologie',
    'fungal infection of the hair': 'Dermatologie',
    'macular degeneration': 'Ophtalmologie',
    'psoriasis': 'Dermatologie',
    'pyogenic skin infection': 'Dermatologie',
    'sebaceous cyst': 'Dermatologie',
    'skin pigmentation disorder': 'Dermatologie',
    'skin polyp': 'Dermatologie',
    'stye': 'Ophtalmologie',

    # --- Rhumatologie & Traumatologie ---
    'arthritis of the hip': 'Rhumatologie',
    'bursitis': 'Rhumatologie',
    'carpal tunnel syndrome': 'Rhumatologie',
    'chronic back pain': 'Rhumatologie',
    'degenerative disc disease': 'Rhumatologie',
    'gout': 'Rhumatologie',
    'herniated disk': 'Rhumatologie',
    'injury to the arm': 'Traumatologie',
    'injury to the leg': 'Traumatologie',
    'injury to the trunk': 'Traumatologie',
    'pain after an operation': 'Traumatologie',
    'spinal stenosis': 'Rhumatologie',
    'spondylosis': 'Rhumatologie',
    'sprain or strain': 'Traumatologie',

    # --- Urologie, Gynécologie, Endocrinologie & Divers ---
    'benign prostatic hyperplasia (bph)': 'Urologie',
    'cystitis': 'Urologie',
    'developmental disability': 'Divers',
    'drug reaction': 'Divers',
    'gum disease': 'Stomatologie',
    'dental caries': 'Stomatologie',
    'hemorrhoids': 'Urologie',
    'hyperemesis gravidarum': 'Gynécologie',
    'hypoglycemia': 'Endocrinologie',
    'idiopathic excessive menstruation': 'Gynécologie',
    'idiopathic irregular menstrual cycle': 'Gynécologie',
    'idiopathic painful menstruation': 'Gynécologie',
    'pelvic inflammatory disease': 'Gynécologie',
    'problem during pregnancy': 'Gynécologie',
    'sepsis': 'Urgences',
    'sickle cell crisis': 'Hématologie',
    'spontaneous abortion': 'Gynécologie',
    'temporary or benign blood in urine': 'Urologie',
    'threatened pregnancy': 'Gynécologie',
    'urinary tract infection': 'Urologie',
    'vaginal cyst': 'Gynécologie',
    'vaginitis': 'Gynécologie',
    'vulvodynia': 'Gynécologie',
    'marijuana abuse': 'Addictologie',
    'drug abuse': 'Addictologie'
}

MALADIES_TRADUCTION = {
    'actinic keratosis': 'kératose actinique',
    'acute bronchiolitis': 'bronchiolite aiguë',
    'acute bronchitis': 'bronchite aiguë',
    'acute bronchospasm': 'bronchospasme aigu',
    'acute kidney injury': 'insuffisance rénale aiguë',
    'acute pancreatitis': 'pancréatite aiguë',
    'acute sinusitis': 'sinusite aiguë',
    'allergy': 'allergie',
    'angina': 'angine de poitrine',
    'anxiety': 'anxiété',
    'appendicitis': 'appendicite',
    'arthritis of the hip': 'arthrose de la hanche',
    'asthma': 'asthme',
    'benign prostatic hyperplasia (bph)': 'hypertrophie bénigne de la prostate',
    'brachial neuritis': 'névrite brachiale',
    'bursitis': 'bursite',
    'carpal tunnel syndrome': 'syndrome du canal carpien',
    'cholecystitis': 'cholécystite',
    'chronic back pain': 'lombalgie chronique',
    'chronic constipation': 'constipation chronique',
    'chronic obstructive pulmonary disease (copd)': 'bronchopneumopathie chronique obstructive (BPCO)',
    'common cold': 'rhume',
    'complex regional pain syndrome': 'syndrome douloureux régional complexe',
    'concussion': 'commotion cérébrale',
    'conjunctivitis': 'conjonctivite',
    'conjunctivitis due to allergy': 'conjonctivite allergique',
    'contact dermatitis': 'eczéma de contact',
    'cornea infection': 'infection de la cornée',
    'croup': 'croup (laryngo-trachéo-bronchite)',
    'cystitis': 'cystite',
    'degenerative disc disease': 'discopathie dégénérative',
    'dental caries': 'carie dentaire',
    'depression': 'dépression',
    'developmental disability': 'trouble du développement',
    'diaper rash': 'érythème fessier du nourrisson',
    'diverticulitis': 'diverticulite',
    'drug reaction': 'réaction indésirable à un médicament',
    'ear drum damage': 'perforation du tympan',
    'eczema': 'eczéma',
    'esophagitis': 'œsophagite',
    'eustachian tube dysfunction (ear disorder)': "dysfonctionnement de la trompe d'Eustache",
    'fungal infection of the hair': 'teigne du cuir chevelu',
    'gallstone': 'calcul biliaire',
    'gastrointestinal hemorrhage': 'hémorragie gastro-intestinale',
    'gout': 'goutte',
    'gum disease': 'gingivite (maladie des gencives)',
    'heart attack': 'infarctus du myocarde (crise cardiaque)',
    'heart failure': 'insuffisance cardiaque',
    'hemorrhoids': 'hémorroïdes',
    'herniated disk': 'hernie discale',
    'hiatal hernia': 'hernie hiatale',
    'hyperemesis gravidarum': 'hyperémèse gravidique',
    'hypertensive heart disease': 'cardiopathie hypertensive',
    'hypoglycemia': 'hypoglycémie',
    'idiopathic excessive menstruation': 'règles anormalement abondantes',
    'idiopathic irregular menstrual cycle': 'cycles menstruels irréguliers',
    'idiopathic painful menstruation': 'règles douloureuses',
    'infectious gastroenteritis': 'gastro-entérite infectieuse',
    'injury to the arm': 'blessure au bras',
    'injury to the leg': 'blessure à la jambe',
    'injury to the trunk': 'blessure au torse',
    'liver disease': 'maladie du foie',
    'macular degeneration': 'dégénérescence maculaire (DMLA)',
    'marijuana abuse': 'abus de cannabis',
    'multiple sclerosis': 'sclérose en plaques',
    'noninfectious gastroenteritis': 'gastro-entérite non infectieuse',
    'nose disorder': 'affection nasale',
    'obstructive sleep apnea (osa)': 'apnée obstructive du sommeil',
    "otitis externa (swimmer's ear)": "otite externe (oreille du nageur)",
    'otitis media': 'otite moyenne',
    'pain after an operation': 'douleur postopératoire',
    'panic disorder': 'trouble panique',
    'pelvic inflammatory disease': 'maladie inflammatoire pelvienne',
    'peripheral nerve disorder': 'neuropathie périphérique',
    'personality disorder': 'trouble de la personnalité',
    'pneumonia': 'pneumonie',
    'problem during pregnancy': 'complication pendant la grossesse',
    'psoriasis': 'psoriasis',
    'pyogenic skin infection': 'pyodermite (infection purulente de la peau)',
    'rectal disorder': 'affection rectale',
    'schizophrenia': 'schizophrénie',
    'seasonal allergies (hay fever)': 'rhume des foins (rhinite allergique)',
    'sebaceous cyst': 'kyste sébacé',
    'sepsis': 'septicémie (sepsis)',
    'sickle cell crisis': 'crise drépanocytaire',
    'sinus bradycardia': 'bradycardie sinusale',
    'skin pigmentation disorder': 'trouble de la pigmentation de la peau',
    'skin polyp': 'polype cutané',
    'spinal stenosis': 'sténose spinale',
    'spondylosis': 'spondylarthrose',
    'spontaneous abortion': 'fausse couche spontanée',
    'sprain or strain': 'entorse ou foulure',
    'strep throat': 'angine à streptocoque',
    'stye': 'orgelet',
    'temporary or benign blood in urine': 'présence temporaire de sang dans les urines',
    'threatened pregnancy': 'menace de fausse couche',
    'urinary tract infection': 'infection urinaire',
    'vaginal cyst': 'kyste vaginal',
    'vaginitis': 'vaginite',
    'vulvodynia': 'vulvodynie'
}
